hoge2

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -8,3 +8,9 @@ LIB_PATH="$(pwd)/lib"
 
 echo $LIB_PATH > $PTH_PATH
 
+if [ $? -eq 0 ] ; then
+    echo "Installed"
+else
+    echo "Error"
+fi
+
